const data_str = "[\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9b1\",\n" +
    "       \"name\":\"Краторная булка N-200i\",\n" +
    "       \"type\":\"bun\",\n" +
    "       \"proteins\":80,\n" +
    "       \"fat\":24,\n" +
    "       \"carbohydrates\":53,\n" +
    "       \"calories\":420,\n" +
    "       \"price\":1255,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/bun-02.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/bun-02-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/bun-02-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9b5\",\n" +
    "       \"name\":\"Говяжий метеорит (отбивная)\",\n" +
    "       \"type\":\"main\",\n" +
    "       \"proteins\":800,\n" +
    "       \"fat\":800,\n" +
    "       \"carbohydrates\":300,\n" +
    "       \"calories\":2674,\n" +
    "       \"price\":3000,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/meat-04.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/meat-04-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/meat-04-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9b6\",\n" +
    "       \"name\":\"Биокотлета из марсианской Магнолии\",\n" +
    "       \"type\":\"main\",\n" +
    "       \"proteins\":420,\n" +
    "       \"fat\":142,\n" +
    "       \"carbohydrates\":242,\n" +
    "       \"calories\":4242,\n" +
    "       \"price\":424,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/meat-01.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/meat-01-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/meat-01-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9b7\",\n" +
    "       \"name\":\"Соус Spicy-X\",\n" +
    "       \"type\":\"sauce\",\n" +
    "       \"proteins\":30,\n" +
    "       \"fat\":20,\n" +
    "       \"carbohydrates\":40,\n" +
    "       \"calories\":30,\n" +
    "       \"price\":90,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/sauce-02.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/sauce-02-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/sauce-02-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9b4\",\n" +
    "       \"name\":\"Мясо бессмертных моллюсков Protostomia\",\n" +
    "       \"type\":\"main\",\n" +
    "       \"proteins\":433,\n" +
    "       \"fat\":244,\n" +
    "       \"carbohydrates\":33,\n" +
    "       \"calories\":420,\n" +
    "       \"price\":1337,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/meat-02.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/meat-02-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/meat-02-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9b9\",\n" +
    "       \"name\":\"Соус традиционный галактический\",\n" +
    "       \"type\":\"sauce\",\n" +
    "       \"proteins\":42,\n" +
    "       \"fat\":24,\n" +
    "       \"carbohydrates\":42,\n" +
    "       \"calories\":99,\n" +
    "       \"price\":15,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/sauce-03.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/sauce-03-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/sauce-03-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9b8\",\n" +
    "       \"name\":\"Соус фирменный Space Sauce\",\n" +
    "       \"type\":\"sauce\",\n" +
    "       \"proteins\":50,\n" +
    "       \"fat\":22,\n" +
    "       \"carbohydrates\":11,\n" +
    "       \"calories\":14,\n" +
    "       \"price\":80,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/sauce-04.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/sauce-04-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/sauce-04-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9bc\",\n" +
    "       \"name\":\"Плоды Фалленианского дерева\",\n" +
    "       \"type\":\"main\",\n" +
    "       \"proteins\":20,\n" +
    "       \"fat\":5,\n" +
    "       \"carbohydrates\":55,\n" +
    "       \"calories\":77,\n" +
    "       \"price\":874,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/sp_1.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/sp_1-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/sp_1-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9bb\",\n" +
    "       \"name\":\"Хрустящие минеральные кольца\",\n" +
    "       \"type\":\"main\",\n" +
    "       \"proteins\":808,\n" +
    "       \"fat\":689,\n" +
    "       \"carbohydrates\":609,\n" +
    "       \"calories\":986,\n" +
    "       \"price\":300,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/mineral_rings.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/mineral_rings-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/mineral_rings-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9ba\",\n" +
    "       \"name\":\"Соус с шипами Антарианского плоскоходца\",\n" +
    "       \"type\":\"sauce\",\n" +
    "       \"proteins\":101,\n" +
    "       \"fat\":99,\n" +
    "       \"carbohydrates\":100,\n" +
    "       \"calories\":100,\n" +
    "       \"price\":88,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/sauce-01.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/sauce-01-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/sauce-01-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9bd\",\n" +
    "       \"name\":\"Кристаллы марсианских альфа-сахаридов\",\n" +
    "       \"type\":\"main\",\n" +
    "       \"proteins\":234,\n" +
    "       \"fat\":432,\n" +
    "       \"carbohydrates\":111,\n" +
    "       \"calories\":189,\n" +
    "       \"price\":762,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/core.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/core-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/core-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9be\",\n" +
    "       \"name\":\"Мини-салат Экзо-Плантаго\",\n" +
    "       \"type\":\"main\",\n" +
    "       \"proteins\":1,\n" +
    "       \"fat\":2,\n" +
    "       \"carbohydrates\":3,\n" +
    "       \"calories\":6,\n" +
    "       \"price\":4400,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/salad.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/salad-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/salad-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9b3\",\n" +
    "       \"name\":\"Филе Люминесцентного тетраодонтимформа\",\n" +
    "       \"type\":\"main\",\n" +
    "       \"proteins\":44,\n" +
    "       \"fat\":26,\n" +
    "       \"carbohydrates\":85,\n" +
    "       \"calories\":643,\n" +
    "       \"price\":988,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/meat-03.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/meat-03-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/meat-03-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9bf\",\n" +
    "       \"name\":\"Сыр с астероидной плесенью\",\n" +
    "       \"type\":\"main\",\n" +
    "       \"proteins\":84,\n" +
    "       \"fat\":48,\n" +
    "       \"carbohydrates\":420,\n" +
    "       \"calories\":3377,\n" +
    "       \"price\":4142,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/cheese.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/cheese-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/cheese-large.png\",\n" +
    "       \"__v\":0\n" +
    "    },\n" +
    "    {\n" +
    "       \"_id\":\"60666c42cc7b410027a1a9b2\",\n" +
    "       \"name\":\"Флюоресцентная булка R2-D3\",\n" +
    "       \"type\":\"bun\",\n" +
    "       \"proteins\":44,\n" +
    "       \"fat\":26,\n" +
    "       \"carbohydrates\":85,\n" +
    "       \"calories\":643,\n" +
    "       \"price\":988,\n" +
    "       \"image\":\"https://code.s3.yandex.net/react/code/bun-01.png\",\n" +
    "       \"image_mobile\":\"https://code.s3.yandex.net/react/code/bun-01-mobile.png\",\n" +
    "       \"image_large\":\"https://code.s3.yandex.net/react/code/bun-01-large.png\",\n" +
    "       \"__v\":0\n" +
    "    }\n" +
    " ]";

const data = JSON.parse(data_str);

export default data;