# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      # View list of checkout files
      - name: View list of checkout files
        run: ls
        
      # connect to ssh
      - name: connect to ssh
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          ssh u1016303:"$SSH_PASS"@37.140.192.184
          ls
          
      # connect to ftp
      - name: connect to ftp
        run: |
          HOST='ftp.example.com'
          USER='yourid'
          PASSWD='yourpw'
          FILE='file.txt'

          ftp -n 37.140.192.184 <<END_SCRIPT
          quote USER u1016303_testuse
          quote PASS dR6sC4eJ9pkA8w
          binary
          put README.md
          quit
          END_SCRIPT
